rootProject.name = 'web-evaluator'

include 'app'
include 'core'
include 'api'
include 'auth'
include 'orchestrator'
include 'scenario-bdd'
include 'scenario-exploratory'
include 'scenario-monkey'
include 'scenario-ai'
include 'crawler'
include 'ui-actions'
include 'ai-gateway'
include 'oracle'
include 'reporting'
include 'security'
