plugins {
    id 'java-library'
}

dependencies {
    api project(':core')
    api project(':ai-gateway')

    implementation 'org.projectlombok:lombok:' + lombokVersion
    annotationProcessor 'org.projectlombok:lombok:' + lombokVersion

    testImplementation 'org.junit.jupiter:junit-jupiter:' + junitJupiterVersion
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
