plugins {
    id 'java-library'
}

dependencies {
    api project(':core')
    api project(':api')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'org.projectlombok:lombok:' + lombokVersion
    annotationProcessor 'org.projectlombok:lombok:' + lombokVersion

    testImplementation 'org.junit.jupiter:junit-jupiter:' + junitJupiterVersion
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
