plugins {
    id 'java-library'
}

dependencies {
    api project(':core')
    api project(':security')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.projectlombok:lombok:' + lombokVersion
    annotationProcessor 'org.projectlombok:lombok:' + lombokVersion

    testImplementation 'org.springframework.boot:spring-boot-starter-web-test'
    testImplementation 'org.junit.jupiter:junit-jupiter:' + junitJupiterVersion
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
